### ISSUE TITLE
[PE-D][Tester B] View command error message missing

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103-W14-2/tp#168]
Command input: `edit id/e m/hi`

![image.png](https://raw.githubusercontent.com/adammangzijun/ped/main/files/5e687918-3fc8-43ac-a705-11477df13165.png)

Advisable to have error message if there's any invalid input. 

1. In general i think your commands does not take into account id invalid inputs
, as such no matter what i write after that, nothing happens

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: adammangzijun/ped#9

**Comment by jacobcuison** [comment]
Duplicate to #163
