### ISSUE TITLE
[PE-D][Tester B] Edit A Meeting UG bug

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103-W14-2/tp#169]
![image.png](https://raw.githubusercontent.com/adammangzijun/ped/main/files/3375f61a-beb8-4537-8639-c0d0ac297999.png)

Maybe it's better to put date or dateTime, rather than time? Just a minor error.

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: adammangzijun/ped#10

**Comment by chiayunrong** [comment]
Not a bug.
