### ISSUE TITLE
[PE-D][Tester D] Duplicate meetings handling choice is suboptimal

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103-W14-2/tp#179]
The current way of handling duplicate meetings is that, a meeting is only considered to be a duplicate if they have the same name.

Problematic behaviour:
1. Users are not allowed to add meetings with the same name(which might be scheduled on a different time)
1. Users are allowed to add meetings on the same time(which is a clash in meeting scheduling and should notify users about it)

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: yucongkoo/ped#8

**Comment by chiayunrong** [comment]
For point 1. I think its fine to not add meetings with the same name. Users can name their meetings like "Discuss CS2103 #1" and "Discuss CS2103 #2" which seems fine to me as it allows users to visually distinguish their meetings without viewing them.
For point 2. There is no problem with having multiple meetings at the same time. Users can choose to attend either 1 of the clashing meetings if they want to.
